// Code generated by docuconf. DO NOT EDIT.
package orders

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind: "ConfigContract"
	metadata: {
		name: "orders"
		generator: {language: "kotlin", sdk: "docuconf-hoplite", version: "0.1.0"}
	}
	vars: {
		ALLOWED_ORIGINS: {
			type: "list"
			description: "Origins allowed to call the API (CORS)"
			configKey: "allowedOrigins"
			items: "string"
			encoding: "csv"
			minItems: 1
			default: ["http://localhost:3000"]
		}
		DATABASE_URL: {
			type: "url"
			description: "Postgres connection URL for the orders database"
			required: true
			secret: true
			configKey: "databaseUrl"
			schemes: ["postgres"]
			maxLength: 2048
		}
		LOG_LEVEL: {
			type: "enum"
			description: "Minimum level of log messages"
			configKey: "logLevel"
			values: ["debug", "info", "warn", "error"]
			default: "info"
		}
		PORT: {
			type: "int"
			description: "HTTP listen port"
			configKey: "port"
			min: 1
			max: 65535
			default: 8080
		}
		REQUEST_TIMEOUT: {
			type: "duration"
			description: "Time limit for handling one request"
			configKey: "requestTimeout"
			encoding: "iso8601"
			min: "1s"
			max: "5m"
			default: "30s"
		}
		WEBHOOK_KEYS: {
			type: "keySet"
			description: "Keys that verify the signature on incoming payment webhooks"
			details: "A webhook is accepted when it is signed with any key in the set, so the key can be rotated\nwithout turning webhooks away; the generated docs list the rotation steps. Each key is 32 to\n256 characters, so an empty or truncated key fails at boot. Without this variable, the service\nrejects every webhook."
			secret: true
			configKey: "webhookKeys"
			encoding: "csv"
			minKeys: 1
			maxKeys: 2
			keyMinLength: 32
			keyMaxLength: 256
		}
		WORKER_COUNT: {
			type: "int"
			description: "Number of background workers that process orders"
			details: "A KDoc works instead of @Doc: its first sentence is the description, and the rest is the details,\nlonger docs for `docuconf docs`. Each worker holds one connection from the pool of `databaseUrl`,\nso keep this below the database's connection limit.\n\n- Raise it when the order queue backs up.\n- Lower it when the database is the bottleneck."
			configKey: "workerCount"
			min: 1
			max: 64
			default: 4
		}
	}
}
