// What each language SDK supports today, taken from each repository's code and
// README (October 2026). Conformance results come from each SDK's conformance runner. Update it with the SDKs; the SDK requirements page,
// llms-full.txt and the JSON-LD all read it.

export type SdkRow = {
	language: string;
	repo: string;
	package: string;
	host: string;
	runtime: string;
	types: string;
	lists: string;
	durations: string;
	configFormats: string;
	keystore: string;
	watch: string;
	profiles: string;
	export: string;
	/** Result of the shared conformance suite (112 cases), and the capability tags it skips. */
	conformance: string;
	caveats: string[];
};

export const SDK_ROWS: SdkRow[] = [
	{
		language: 'Go',
		repo: 'docuconf-go',
		package: 'github.com/docuconf/docuconf-go',
		host: 'caarlos0/env v11',
		runtime: 'Go 1.24',
		types: 'all 9',
		lists: 'csv',
		durations: 'go',
		configFormats: 'json, yaml',
		keystore: 'PKCS#12',
		watch: 'all file types',
		profiles: '—',
		export: 'docuconf export -pkg -type',
		conformance: '112 of 112',
		caveats: ['caarlos0/env parses int as 32-bit, so that range is exported.', 'No TOML config files, no JKS keystores.'],
	},
	{
		language: 'TypeScript',
		repo: 'docuconf-js',
		package: '@docuconf/t3 (npm)',
		host: 'T3 Env + Zod 4',
		runtime: 'Node 22.12',
		types: 'all 9',
		lists: 'csv',
		durations: 'go',
		configFormats: 'json, yaml',
		keystore: 'PKCS#12 (JKS: format check)',
		watch: 'all file types',
		profiles: '—',
		export: 'npx docuconf export src/env.ts',
		conformance: '109 of 112 (skips int64, json-schema)',
		caveats: [
			'ESM (.mjs) and CommonJS both supported.',
			'int is limited to the safe-integer range.',
			'Tested with Zod; Valibot and ArkType are untested.',
		],
	},
	{
		language: '.NET',
		repo: 'docuconf-dotnet',
		package: 'Docuconf.Options (NuGet)',
		host: 'Options pattern + appsettings',
		runtime: '.NET 8, .NET 10',
		types: 'all 9',
		lists: 'indexed',
		durations: 'timespan',
		configFormats: 'json',
		keystore: 'PKCS#12',
		watch: 'tls, caBundle, keystore, binary',
		profiles: 'appsettings.{Environment}.json',
		export: 'dotnet app.dll docuconf export',
		conformance: '110 of 112 (skips json-schema)',
		caveats: [
			'Platform-mounted appsettings overlays load through AddDocuconfOverlays<T>().',
			'Export runs at runtime; a build-time source generator is planned.',
		],
	},
	{
		language: 'Python',
		repo: 'docuconf-python',
		package: 'docuconf-pydantic (PyPI)',
		host: 'pydantic-settings 2',
		runtime: 'Python 3.10',
		types: 'all 9',
		lists: 'json (csv opt-in)',
		durations: 'iso8601',
		configFormats: 'json, yaml, toml',
		keystore: 'PKCS#12',
		watch: 'all file types',
		profiles: '—',
		export: 'docuconf export mod:Settings',
		conformance: '112 of 112 (json-schema with the jsonschema extra)',
		caveats: ['No JKS keystores.', 'No profiles.'],
	},
	{
		language: 'Ruby',
		repo: 'docuconf-ruby',
		package: 'docuconf-anyway (RubyGems)',
		host: 'anyway_config 2',
		runtime: 'Ruby 3.2',
		types: 'all 9',
		lists: 'csv',
		durations: 'iso8601',
		configFormats: 'json, yaml, toml',
		keystore: 'PKCS#12 (JKS: format check)',
		watch: 'all file types',
		profiles: 'Rails YAML (RAILS_ENV)',
		export: 'rails docuconf:export',
		conformance: '112 of 112',
		caveats: ['Rails credentials must be excluded explicitly.', 'TOML needs the tomlrb gem.'],
	},
	{
		language: 'Java',
		repo: 'docuconf-java',
		package: 'dev.docuconf:docuconf-spring (Maven)',
		host: 'Spring Boot 3 / 4 @ConfigurationProperties',
		runtime: 'Java 17',
		types: 'all 9',
		lists: 'csv',
		durations: 'iso8601',
		configFormats: 'json, yaml, toml',
		keystore: 'PKCS#12, JKS',
		watch: 'all file types',
		profiles: 'application-{profile}.yml',
		export: 'annotation processor at compile time',
		conformance: '112 of 112',
		caveats: ['Several active profiles at once (a,b) are not supported yet.'],
	},
	{
		language: 'Kotlin',
		repo: 'docuconf-kotlin',
		package: 'dev.docuconf:docuconf-hoplite (Maven)',
		host: 'Hoplite 3',
		runtime: 'JDK 17, Kotlin 2.2',
		types: 'all 9',
		lists: 'csv',
		durations: 'iso8601',
		configFormats: 'json, yaml, toml',
		keystore: 'PKCS#12, JKS',
		watch: 'not offered',
		profiles: '—',
		export: 'Docuconf.exportCue()',
		conformance: '112 of 112',
		caveats: ['JVM target only so far; the core module is Kotlin Multiplatform-ready.', 'No reload: watch.'],
	},
	{
		language: 'Rust',
		repo: 'docuconf-rust',
		package: 'docuconf (crates.io)',
		host: 'figment + serde',
		runtime: 'Rust 1.89',
		types: 'all 9',
		lists: 'json',
		durations: 'go',
		configFormats: 'json, yaml, toml',
		keystore: 'PKCS#12',
		watch: 'rejected at declaration',
		profiles: 'figment profiles',
		export: 'docuconf::export()',
		conformance: '112 of 112',
		caveats: ['No reload: watch.', 'No JKS keystores.'],
	},
	{
		language: 'Swift',
		repo: 'docuconf-swift',
		package: 'Docuconf (SwiftPM)',
		host: 'swift-configuration',
		runtime: 'Swift 6.2',
		types: 'all 9',
		lists: 'csv',
		durations: 'seconds',
		configFormats: 'json, yaml',
		keystore: 'PKCS#12, JKS (integrity check)',
		watch: 'when the app consumes changes',
		profiles: '—',
		export: 'app docuconf-export',
		conformance: '110 of 112 (skips json-schema)',
		caveats: ['Built and tested on Linux; macOS and iOS builds are untested.', 'No TOML, no profiles.'],
	},
	{
		language: 'Elixir',
		repo: 'docuconf-elixir',
		package: 'docuconf (Hex)',
		host: 'config/runtime.exs',
		runtime: 'Elixir 1.18, OTP 25',
		types: 'all 9',
		lists: 'csv',
		durations: 'go',
		configFormats: 'json (yaml, toml via a decoder)',
		keystore: 'PKCS#12, JKS (integrity check)',
		watch: 'with Docuconf.Watcher',
		profiles: '—',
		export: 'mix docuconf.export',
		conformance: '112 of 112',
		caveats: ['Watched files reload only while the app supervises Docuconf.Watcher.'],
	},
	{
		language: 'Gleam',
		repo: 'docuconf-gleam',
		package: 'docuconf (Hex)',
		host: 'envoy + gleam/dynamic/decode',
		runtime: 'Gleam 1.14 (Erlang or JavaScript)',
		types: 'all 9',
		lists: 'csv',
		durations: 'go',
		configFormats: 'json (others via a parser)',
		keystore: 'format check only',
		watch: 'not offered',
		profiles: '—',
		export: 'docuconf.write_contract()',
		conformance: '110 of 112 on Erlang, 109 on JavaScript (skips json-schema; int64 on JavaScript)',
		caveats: [
			'Keystores are not opened with their password yet.',
			'On the JavaScript target, integers beyond 2^53 lose precision.',
			'The Hex package name is shared with the Elixir SDK; one will be renamed.',
		],
	},
];
