// Code generated by docuconf. DO NOT EDIT.
package orders_batch

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "orders-batch"
		generator: {
			language: "cobol"
			sdk:      "docuconf-cobol"
			version:  "0.1.0"
		}
	}
	vars: {
		ALLOWED_ORIGINS: {
			type:        "list"
			description: "Origins whose orders the job accepts"
			default: ["http://localhost:3000"]
			encoding:      "csv"
			items:         "string"
			separator:     ","
			minItems:      1
			maxItems:      8
			itemMaxLength: 64
		}
		DATABASE_URL: {
			type:        "url"
			description: "Postgres connection string of the orders database"
			required:    true
			secret:      true
			maxLength:   200
			schemes: ["postgres"]
		}
		LOG_LEVEL: {
			type:        "enum"
			description: "Log verbosity"
			default:     "info"
			values: ["debug", "info", "warn", "error"]
		}
		PORT: {
			type:        "int"
			description: "Port of the Prometheus metrics endpoint"
			default:     8080
			min:         1
			max:         65535
		}
		REQUEST_TIMEOUT: {
			type:        "duration"
			description: "Time allowed for each database call, in milliseconds"
			default:     "30s"
			min:         "1s"
			max:         "5m"
			encoding:    "go"
		}
		WEBHOOK_KEYS: {
			type:         "keySet"
			description:  "Keys that verify the signature on incoming payment webhooks"
			details:      "A webhook is accepted when it is signed with any key in the\nset, so the key can be rotated without turning webhooks\naway. Each key is 32 to 256 characters, so an empty or\ntruncated key fails at boot. Without this variable, the\nservice rejects every webhook."
			secret:       true
			encoding:     "csv"
			separator:    ","
			minKeys:      1
			maxKeys:      2
			keyMinLength: 32
			keyMaxLength: 256
		}
		WORKER_COUNT: {
			type:        "int"
			description: "Number of workers that share the input"
			details:     "Each worker reads its share of the orders file and holds\none database connection, so keep this at or below the\npool size:\n\n- one connection per worker;\n- plus one for the summary step."
			default:     4
			min:         1
			max:         64
		}
	}
	files: {
		orders: {
			type:        "text"
			description: "The orders to summarise, one per line"
			required:    true
			path:        "/data/orders.txt"
			pathEnv:     "ORDERS_FILE"
			maxSize:     1048576
		}
	}
}
