// Code generated by docuconf. DO NOT EDIT.
package orders

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind: "ConfigContract"
	metadata: {
		name: "orders"
		appVersion: "1.0.0"
		generator: {language: "java", sdk: "docuconf-spring", version: "0.1.0-SNAPSHOT"}
	}
	vars: {
		ORDERS_ALLOWEDORIGINS: {
			type: "list"
			description: "Origins allowed to call the API from a browser"
			configKey: "orders.allowed-origins"
			items: "string"
			encoding: "csv"
			minItems: 1
			default: ["http://localhost:3000"]
		}
		ORDERS_DATABASEURL: {
			type: "url"
			description: "Postgres connection URL for the orders database"
			required: true
			secret: true
			configKey: "orders.database-url"
			schemes: ["postgres"]
		}
		ORDERS_LOGLEVEL: {
			type: "enum"
			description: "Minimum level of the log lines the service writes"
			configKey: "orders.log-level"
			values: ["debug", "info", "warn", "error"]
			default: "info"
		}
		ORDERS_PORT: {
			type: "int"
			description: "HTTP listen port"
			configKey: "orders.port"
			min: 1
			max: 65535
			default: 8080
		}
		ORDERS_REQUESTTIMEOUT: {
			type: "duration"
			description: "Time allowed to answer one request"
			configKey: "orders.request-timeout"
			encoding: "iso8601"
			min: "1s"
			max: "5m"
			default: "30s"
		}
		ORDERS_WORKERCOUNT: {
			type: "int"
			description: "Background workers that process new orders"
			configKey: "orders.worker-count"
			min: 1
			max: 64
			default: 4
		}
	}
}
