// Code generated by docuconf. DO NOT EDIT.
package orders

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind: "ConfigContract"
	metadata: {
		name: "orders"
		generator: {language: "swift", sdk: "docuconf-swift", version: "0.1.0"}
	}
	vars: {
		ALLOWED_ORIGINS: {
			type: "list"
			description: "Origins allowed to call the API (CORS)"
			configKey: "allowed.origins"
			items: "string"
			encoding: "csv"
			minItems: 1
			default: ["http://localhost:3000"]
		}
		DATABASE_URL: {
			type: "url"
			description: "Postgres connection string for the orders database"
			required: true
			secret: true
			configKey: "database.url"
			schemes: ["postgres"]
			maxLength: 2048
		}
		LOG_LEVEL: {
			type: "enum"
			description: "Minimum log level"
			configKey: "log.level"
			values: ["debug", "info", "warn", "error"]
			default: "info"
		}
		PORT: {
			type: "int"
			description: "HTTP listen port"
			configKey: "port"
			min: 1
			max: 65535
			default: 8080
		}
		REQUEST_TIMEOUT: {
			type: "duration"
			description: "Timeout for one request"
			configKey: "request.timeout"
			encoding: "seconds"
			min: "1s"
			max: "5m"
			default: "30s"
		}
		WEBHOOK_KEYS: {
			type: "keySet"
			description: "Keys that verify the signature on incoming payment webhooks"
			details: "A webhook is accepted when it is signed with any key in the set, so the key can be rotated without\nturning webhooks away. Each key is 32 to 256 characters, so an empty or truncated key fails at boot.\nWithout this variable, the service rejects every webhook."
			secret: true
			configKey: "webhook.keys"
			encoding: "csv"
			minKeys: 1
			maxKeys: 2
			keyMinLength: 32
			keyMaxLength: 256
		}
		WORKER_COUNT: {
			type: "int"
			description: "Number of background order workers"
			details: "Each worker takes one order at a time from the queue and holds one database connection, so keep this\nat or below the pool size:\n\n- one connection per worker;\n- plus one for the HTTP handlers."
			configKey: "worker.count"
			min: 1
			max: 64
			default: 4
		}
	}
}
