// Code generated by docuconf. DO NOT EDIT.
package orders

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind: "ConfigContract"
	metadata: {
		name: "orders"
		generator: {
			language: "cpp"
			sdk: "docuconf-cpp"
			version: "0.1.0"
		}
	}
	vars: {
		ALLOWED_ORIGINS: {
			type: "list"
			description: "Origins allowed to call the API (CORS)"
			default: ["http://localhost:3000"]
			items: "string"
			encoding: "csv"
			separator: ","
			minItems: 1
		}
		DATABASE_URL: {
			type: "url"
			description: "Primary Postgres connection string"
			required: true
			secret: true
			maxLength: 2048
			schemes: ["postgres"]
		}
		LOG_LEVEL: {
			type: "enum"
			description: "Minimum log level emitted"
			default: "info"
			values: ["debug", "info", "warn", "error"]
		}
		PORT: {
			type: "int"
			description: "HTTP listen port"
			default: 8080
			min: 1
			max: 65535
		}
		REQUEST_TIMEOUT: {
			type: "duration"
			description: "Time allowed to read a request"
			default: "30s"
			min: "1s"
			max: "5m"
			encoding: "go"
		}
		WEBHOOK_KEYS: {
			type: "list"
			description: "Keys that verify the signature on incoming payment webhooks"
			details: "A webhook is accepted when it is signed with any key in the list, so\nthe key can be rotated without turning webhooks away. To rotate:\n\n 1. add the new key as the second item, and roll out;\n 2. switch the sender to the new key;\n 3. remove the old key, and roll out.\n\nEach key is 32 to 256 characters, so an empty or truncated key fails\nat boot. Without this variable, the service rejects every webhook."
			secret: true
			items: "string"
			encoding: "csv"
			separator: ","
			minItems: 1
			maxItems: 2
			itemMinLength: 32
			itemMaxLength: 256
		}
		WORKER_COUNT: {
			type: "int"
			description: "Number of request worker threads"
			details: "Each worker answers one connection at a time, so this is also the\nnumber of requests served at once. Raise it when requests queue up.\n\nKeep it at or below the database pool size:\n- one connection per worker;\n- plus one for migrations."
			default: 4
			min: 1
			max: 64
		}
	}
}
