// Code generated by docuconf. DO NOT EDIT.
package orders_api

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind: "ConfigContract"
	metadata: {
		name: "orders-api"
		generator: {language: "dotnet", sdk: "Docuconf.Options", version: "0.1.0-alpha.1"}
	}
	vars: {
		ORDERS__ALLOWEDORIGINS: {
			type: "list"
			description: "Origins allowed to call the API from a browser"
			configKey: "Orders:AllowedOrigins"
			items: "string"
			encoding: "indexed"
			minItems: 1
			default: ["http://localhost:3000"]
		}
		ORDERS__DATABASEURL: {
			type: "url"
			description: "Postgres connection string for the orders database"
			required: true
			secret: true
			configKey: "Orders:DatabaseUrl"
			schemes: ["postgres"]
			maxLength: 2048
		}
		ORDERS__LOGLEVEL: {
			type: "enum"
			description: "Minimum level of log messages to write"
			configKey: "Orders:LogLevel"
			values: ["debug", "info", "warn", "error"]
			default: "info"
		}
		ORDERS__PORT: {
			type: "int"
			description: "HTTP listen port"
			configKey: "Orders:Port"
			min: 1
			max: 65535
			default: 8080
		}
		ORDERS__REQUESTTIMEOUT: {
			type: "duration"
			description: "Time allowed to handle one request"
			configKey: "Orders:RequestTimeout"
			encoding: "timespan"
			min: "1s"
			max: "5m"
			default: "30s"
		}
		ORDERS__WORKERCOUNT: {
			type: "int"
			description: "Background workers that process new orders"
			details: "Each worker holds one connection from the pool of `OrdersOptions.DatabaseUrl`, so keep this below the database's connection limit.\n\n- Raise it when the order queue backs up.\n- Lower it when the database is the bottleneck."
			configKey: "Orders:WorkerCount"
			min: 1
			max: 64
			default: 4
		}
	}
}
