// Code generated by docuconf. DO NOT EDIT.
package orders_symfony

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "orders-symfony"
		generator: {
			language: "php"
			sdk:      "docuconf/docuconf"
			version:  "0.1.0"
		}
	}
	vars: {
		ALLOWED_ORIGINS: {
			type:        "list"
			description: "Origins allowed to call the API (CORS)"
			items:       "string"
			encoding:    "csv"
			separator:   ","
			minItems:    1
			default: ["http://localhost:3000"]
		}
		DATABASE_URL: {
			type:        "url"
			description: "Orders database connection string"
			required:    true
			secret:      true
			schemes: ["postgres", "postgresql"]
			maxLength: 2048
		}
		LOG_LEVEL: {
			type:        "enum"
			description: "Minimum log level"
			values: ["debug", "info", "warn", "error"]
			default: "info"
		}
		PORT: {
			type:        "int"
			description: "HTTP listen port"
			min:         1
			max:         65535
			default:     8080
		}
		REQUEST_TIMEOUT: {
			type:        "duration"
			description: "Timeout for each request"
			encoding:    "go"
			min:         "1s"
			max:         "5m"
			default:     "30s"
		}
		WEBHOOK_KEYS: {
			type:         "keySet"
			description:  "Keys that verify the signature on incoming payment webhooks"
			details:      "A webhook is accepted when it is signed with any key in the set. Each key is 32 to 256 characters, so an empty or truncated key fails at boot. Without this variable, the service rejects every webhook."
			secret:       true
			encoding:     "csv"
			separator:    ","
			minKeys:      1
			maxKeys:      2
			keyMinLength: 32
			keyMaxLength: 256
		}
		WORKER_COUNT: {
			type:        "int"
			description: "Number of background workers"
			min:         1
			max:         64
			default:     4
		}
	}
}
