// Code generated by docuconf. DO NOT EDIT.
package orders

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "orders-api"
		generator: {
			language: "ruby"
			sdk:      "docuconf-anyway"
			version:  "0.1.0"
		}
	}
	vars: {
		ALLOWED_ORIGINS: {
			type:        "list"
			description: "CORS origins allowed to call the API"
			configKey:   "orders.allowed_origins"
			items:       "string"
			encoding:    "csv"
			separator:   ","
			minItems:    1
			default: ["http://localhost:3000"]
		}
		DATABASE_URL: {
			type:        "url"
			description: "Postgres connection string for orders"
			required:    true
			secret:      true
			configKey:   "orders.database_url"
			schemes: ["postgres"]
			maxLength: 2048
		}
		LOG_LEVEL: {
			type:        "enum"
			description: "Minimum log level"
			configKey:   "orders.log_level"
			values: ["debug", "info", "warn", "error"]
			default: "info"
		}
		PORT: {
			type:        "int"
			description: "HTTP listen port"
			configKey:   "orders.port"
			min:         1
			max:         65535
			default:     8080
		}
		REQUEST_TIMEOUT: {
			type:        "duration"
			description: "Time allowed to handle one request"
			details:     "How long the server works on one request before it gives up.\n\nRaise it when clients upload large order batches. Keep it below the load\nbalancer's idle timeout, or the client sees a reset rather than a `504`."
			configKey:   "orders.request_timeout"
			encoding:    "iso8601"
			min:         "1s"
			max:         "5m"
			default:     "30s"
		}
		WEBHOOK_KEYS: {
			type:          "list"
			description:   "Keys that verify the signature on incoming payment webhooks"
			details:       "A webhook is accepted when it is signed with any key in the list, so the\nkey can be rotated without turning webhooks away. To rotate:\n\n 1. add the new key as the second item, and roll out;\n 2. switch the sender to the new key;\n 3. remove the old key, and roll out.\n\nEach key is 32 to 256 characters, so an empty or truncated key fails at\nboot. Without this variable, the service rejects every webhook."
			secret:        true
			configKey:     "orders.webhook_keys"
			items:         "string"
			encoding:      "csv"
			separator:     ","
			minItems:      1
			maxItems:      2
			itemMinLength: 32
			itemMaxLength: 256
		}
		WORKER_COUNT: {
			type:        "int"
			description: "Background workers processing orders"
			configKey:   "orders.worker_count"
			min:         1
			max:         64
			default:     4
		}
	}
}
