// Code generated by docuconf. DO NOT EDIT.
package orders

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind: "ConfigContract"
	metadata: {
		name: "orders"
		appVersion: "1.0.0"
		generator: {
			language: "elixir"
			sdk: "docuconf"
			version: "0.1.0"
		}
	}
	vars: {
		ALLOWED_ORIGINS: {
			type: "list"
			description: "Origins allowed to call the API (CORS)"
			items: "string"
			encoding: "csv"
			separator: ","
			minItems: 1
			default: ["http://localhost:3000"]
		}
		DATABASE_URL: {
			type: "url"
			description: "Postgres connection string"
			required: true
			secret: true
			schemes: ["postgres"]
			maxLength: 2048
		}
		LOG_LEVEL: {
			type: "enum"
			description: "Minimum log level"
			values: ["debug", "info", "warning", "error"]
			default: "info"
		}
		PORT: {
			type: "int"
			description: "HTTP listen port"
			min: 1
			max: 65535
			default: 8080
		}
		REQUEST_TIMEOUT: {
			type: "duration"
			description: "Time limit for one request"
			details: "Raise it when clients upload large order batches. Keep it below the load\nbalancer's idle timeout, or the client sees a reset rather than a `504`."
			encoding: "go"
			min: "1s"
			max: "5m"
			default: "30s"
		}
		WEBHOOK_KEYS: {
			type: "keySet"
			description: "Keys that verify the signature on incoming payment webhooks"
			details: "A webhook is accepted when it is signed with any key in the set, so the\nkey can be rotated without turning webhooks away. Each key is 32 to 256\ncharacters, so an empty or truncated key fails at boot. Without this\nvariable, the service rejects every webhook."
			secret: true
			encoding: "csv"
			separator: ","
			minKeys: 1
			maxKeys: 2
			keyMinLength: 32
			keyMaxLength: 256
		}
		WORKER_COUNT: {
			type: "int"
			description: "Order processing workers"
			min: 1
			max: 64
			default: 4
		}
	}
}
